# Generated by Django 4.0.5 on 2022-06-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('position_number', models.BigAutoField(primary_key=True, serialize=False, verbose_name='№')),
                ('order_number', models.IntegerField(verbose_name='заказ №')),
                ('dollar_value', models.IntegerField(verbose_name='стоимость,$')),
                ('delivery_time', models.DateField(verbose_name='срок поставки')),
            ],
        ),
    ]
