version: '3.3'
services:
#    server:
#      build:
#        context: ./
#        dockerfile: ./server/Dockerfile
#      command: python manage.py runserver 0.0.0.0:8000
#      volumes:
#        - ./server:/server
#      ports:
#        - "8000:8000"
#      depends_on:
#        - db
#      environment:
#        DEBUG: 'True'
#        DATABASE_URL: 'postgres://numbers_admin:140944@db:5432/numbers'

    db:
      image: postgres:12.4-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        POSTGRES_DB: numbers
        POSTGRES_USER: numbers_admin
        POSTGRES_PASSWORD: 140944

    script:
      build:
        context: ./
        dockerfile: ../sync_script/Dockerfile
      command: python3 get_data_sheet.py
      depends_on:
        - db
#        - server




volumes:
  postgres_data:

